# Generated by Django 3.0 on 2020-01-22 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Samochod',
            fields=[
                ('marka', models.CharField(max_length=30, verbose_name='Nazwa marki')),
                ('model', models.CharField(max_length=20, verbose_name='Nazwa modelu')),
                ('data_produkcji', models.DateTimeField(verbose_name='data produkcji')),
                ('opis', models.TextField(blank=True)),
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('cena', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='sell',
            fields=[
                ('kupujacy', models.CharField(max_length=30, verbose_name='Kupujacy')),
                ('marka', models.CharField(max_length=30, verbose_name='Nazwa marki')),
                ('model', models.CharField(max_length=20, verbose_name='Nazwa modelu')),
                ('Cena', models.FloatField(default=0.0)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='wiadomosci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick', models.CharField(max_length=30, verbose_name='nick')),
                ('wiadomosc', models.TextField()),
            ],
        ),
    ]
