# Generated by Django 3.0 on 2020-01-23 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='proba',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('uczestnik', models.CharField(max_length=40, verbose_name='Uczestnik')),
            ],
        ),
    ]
