# Generated by Django 3.0 on 2020-01-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0002_proba'),
    ]

    operations = [
        migrations.AddField(
            model_name='samochod',
            name='link',
            field=models.CharField(max_length=200, null=True, verbose_name='zdjecie'),
        ),
    ]
