# Generated by Django 3.0 on 2020-01-29 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0003_samochod_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='proba',
            name='auto',
            field=models.CharField(max_length=100, null=True, verbose_name='auto'),
        ),
    ]
