# Generated by Django 3.0 on 2020-01-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_proba_auto'),
    ]

    operations = [
        migrations.AddField(
            model_name='wiadomosci',
            name='data',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
